---
- name: "centos | config plugins"
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: plugins
    value: 1
  tags:
    packages
    packages::config

- name: "centos | config proxy"
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy
    value: "{{ packages_proxy }}"
  when: not packages_proxy is none
  tags:
    packages
    packages::config

- name: "centos | config proxy_username"
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy_username
    value: "{{ packages_proxy_username }}"
  when: not packages_proxy_username is none
  tags:
    packages
    packages::config

- name: "centos | config proxy_password"
  ini_file:
    dest: /etc/yum.conf
    section: main
    option: proxy_password
    value: "{{ packages_proxy_password }}"
  when: not packages_proxy_password is none
  tags:
    packages
    packages::config
