---
- name: "debian | config"
  ansible.builtin.template:
    src: config/{{ config_item.src }}
    dest: /etc/apt/apt.conf.d/{{ config_item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items: "{{ packages_configs }}"
  loop_control:
    loop_var: config_item
