---
# tasks file for packages

# tasks file for zabbix-agent
- name: "common | set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
   - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
   - "os-{{ ansible_distribution }}.yml"
   - "os-default.yml"
  tags:
    - packages
    - repository

# Debian(setup)  specific tasks
- include: repository-Debian.yml
  when: ansible_distribution in ('Debian', 'Ubuntu')

# RedHat(setup) specific tasks
- include: repository-CentOS.yml
  when: ansible_distribution in ('CentOS', 'RedHat')
