---
# tasks file for packages

# tasks file for zabbix-agent
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - packages
    - repository

# Debian(setup)  specific tasks
- include: repository-Debian.yml
  when: "ansible_os_family == 'Debian'"

# RedHat(setup) specific tasks
- include: repository-RedHat.yml
  when: "ansible_os_family == 'RedHat'"
