---
# tasks file for packages

- name: "set os specific variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
  tags:
    - packages
    - packages:config
    - packages:repository
    - packages:packages

- name: include config tasks
  include: config-{{ ansible_os_family }}.yml
  tags:
    - packages
    - packages:config

- name: include repository tasks
  include: repository-{{ ansible_os_family }}.yml
  tags:
    - packages
    - packages:repository

- name: include packages tasks
  include: packages-{{ ansible_os_family }}.yml
  tags:
    - packages
    - packages:packages
