---
# tasks file for packages

- name: "set os specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "os-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "os-{{ ansible_distribution }}.yml"
    - "os-default.yml"
  tags: always

- name: include config tasks
  ansible.builtin.include_tasks:
    file: config-{{ ansible_os_family }}.yml
    apply:
      tags:
        - packages
        - packages:config
  tags:
    - always
  when: packages_enabled

- name: include repository tasks
  ansible.builtin.include_tasks:
    file: repository-{{ ansible_os_family }}.yml
    apply:
      tags:
        - packages
        - packages:repository
  tags: always
  when: packages_enabled

- name: include packages tasks
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - packages
        - packages:packages
  tags: always
  when: packages_enabled
